version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 'make'
      - persist_to_workspace:
          root: .
          paths:
            - terminal
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 'chmod 755 test'
      - run: './test'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
