version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 'make'
      - persist_to_workspace:
          root: .
          paths:
            - terminal
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 'chmod 755 test'
      - run: './test'
  doxygen:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 'sudo apt-get update'
      - run: 'sudo apt-get install doxygen'
      - run: 'sudo apt-get install graphviz'
      - run: 'doxygen -g'
      - run: 'doxygen Doxyfile'
      - run: 'sudo apt-get install texlive-full'
      - run: 'sudo apt-get install texmaker'
      - run: 'latex make'
      - store_artifacts:
          path: .
          destination: Doxyfile

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - doxygen:
          requires:
            - build