version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 'make'
      - persist_to_workspace:
          root: .
          paths:
            - terminal
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 'chmod 755 test'
      - run: './test'
  unittest:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: 'Install GoogleTest'
          command: |
            git submodule init
            git submodule update
            sudo apt-get -y -q update
            sudo apt-get -y -q install libgtest-dev
            sudo apt-get -y -q install cmake
            cd /usr/src/gtest
            sudo cmake CMakeLists.txt
            sudo make
            sudo cp *.a /usr/lib
            cd $HOME/project
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - doxygen:
          requires:
            - build
      - unittest:
          requires:
            - build
