version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 'make'
      - persist_to_workspace:
          root: .
          paths:
            - terminal
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 'chmod 755 test'
      - run: './test'
  doxygen:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 'sudo apt-get update'
      - run: 'sudo apt-get install doxygen'
      - run: 'sudo apt-get install graphviz'
      - run: 'doxygen -g'
      - run: 'doxygen Doxyfile'
      - run: 'sudo apt-get install texmaker'
      - run: 'doxygen -w latex header.tex footer.tex doxygen.sty'
      - store_artifacts:
          path: .
          destination: Doxyfiles
  unittest:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 'mkdir -p ~/build'
      - run: 'cd ~/build'
      - run: 'git clone https://github.com/google/googletest.git'
      - run: 'sudo apt-get install cmake'
      - run: 'GTEST_DIR=~/build/googletest/googletest'
      - run: 'cd GTEST_DIR'
      - run: 'g++ -isystem ${GTEST_DIR}/include -I${GTEST_DIR} -pthread -c ${GTEST_DIR}/src/gtest-all.cc'
      - run: 'ar -rv libgtest.a gtest-all.o'
      - run: 'cd ~/build/googletest/googletest/'
      - run: 'ls *.a'
      - run: 'cd ${GTEST_DIR}/make'
      - run: 'make'
      - run: './cmdtest'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - doxygen:
          requires:
            - build
      - unittest:
          requires:
            - build
